name: boilerplate2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # in-house lib
  deeper: ^0.0.1
  mvvm_bloc: ^1.0.4
  bloc_builder: ^1.0.1
  flutter_live_data: ^1.0.1

  # Third-Party lib
  provider: ^4.3.2+2
  get_it: ^3.0.3
  url_launcher: ^5.0.2
  dartz: ^0.8.9
  logger: ^0.7.0
  logger_flutter: ^0.7.1
  intl: ^0.16.1
  rxdart: ^0.24.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+6
  dio: ^3.0.7
  path_provider: ^1.6.18
  dynamic_theme: ^1.0.0
  event_bus: ^1.1.1
  easy_localization: ^2.3.3
  floor: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_verify: ^1.0.0
  json_serializable: ^3.2.0 # Used by tests. Not required to use `json_serializable`.
  mockito: ^4.1.1
  path: ^1.5.1
  test: ^1.6.0
  floor_generator: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/mock/
    - assets/fonts/
  fonts:
    - family: BaiJamjuree
      fonts:
        - asset: assets/fonts/BaiJamjuree-Bold.ttf
        - asset: assets/fonts/BaiJamjuree-BoldItalic.ttf
        - asset: assets/fonts/BaiJamjuree-ExtraLight.ttf
        - asset: assets/fonts/BaiJamjuree-ExtraLightItalic.ttf
        - asset: assets/fonts/BaiJamjuree-RegularItalic.ttf
        - asset: assets/fonts/BaiJamjuree-Light.ttf
        - asset: assets/fonts/BaiJamjuree-LightItalic.ttf
        - asset: assets/fonts/BaiJamjuree-Medium.ttf
        - asset: assets/fonts/BaiJamjuree-MediumItalic.ttf
        - asset: assets/fonts/BaiJamjuree-Regular.ttf
        - asset: assets/fonts/BaiJamjuree-SemiBold.ttf
        - asset: assets/fonts/BaiJamjuree-SemiBoldItalic.ttf